{% set name = "databricks-sdk" %}
{% set version = "0.63.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
    sha256: f141bc810b4145e93e628a0e159ea41806440aed0cd17adddd252d65d1968465
  - url: https://github.com/databricks/{{ name }}-py/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 9e57f969374b4240d93faea3d090d65d904c0db4da949bb622f14cfd166ec262
    folder: gh_src

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<37]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools >=42
    
  run:
    - python
    - requests >=2.28.1,<3
    - google-auth >=2.0,<3
  run_constrained:
    - ipython >=8,<10
    - ipywidgets >=8,<9

# skip test_init_file_contents because wants to verify the hash of
# the source file "databricks/__init__.py", not relevant for us.
{% set tests_to_skip = " test_init_file_contents" %}
# ImportError: Open AI is not installed. Please install the Databricks SDK with the following command `pip install databricks-sdk[openai]`
{% set tests_to_skip = tests_to_skip + " or test_open_ai_client" %}
{% set tests_to_skip = tests_to_skip + " or test_langchain_open_ai_client" %}

test:
  source_files:
    - gh_src/tests
  imports:
    - databricks
    - databricks.sdk
  requires:
    - pip
    - pytest
    - pytest-xdist
    - pytest-mock
    - pyfakefs
    - requests-mock
  commands:
    - pip check
    - cd gh_src
    - pytest tests -vv -m "not integration and not benchmark" -k "not ({{ tests_to_skip }})"

about:
  home: https://github.com/databricks/databricks-sdk-py
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE
  summary: Databricks SDK for Python (Experimental)
  description: |
    The Databricks SDK for Python includes functionality to accelerate development with Python for the Databricks Lakehouse.
    It covers all public Databricks REST API operations.
  doc_url: https://databricks-sdk-py.readthedocs.io
  dev_url: https://github.com/databricks/databricks-sdk-py

extra:
  recipe-maintainers:
    - jasongrout-db
    - nfx
    - monaldoj
