{% set name = "databricks-sdk" %}
{% set version = "0.6.0" %}
{% set sha256 = "791f4f0809eb3920ef4ef0a6b20a42673efd0deef1b2e73c3ec63aca8e3632fa" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/databricks-sdk-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - requests >=2.28.1,<2.29.0

test:
  imports:
    - databricks
    - databricks.sdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/databricks/databricks-sdk-py
  summary: Databricks SDK for Python (Experimental)
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - jasongrout-db
    - nfx
